name: e2e

on:
  pull_request:
    branches: [ '**' ]

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Playwright E2E (app)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.19'

      - name: Install dependencies
        run: bun install

      - name: Install Playwright browsers and OS deps
        run: bun run e2e:install

      # Optional: build once; globalSetup also builds, but this speeds up and fails fast
      - name: Build app
        run: bun run build
        env:
          NODE_ENV: test

      - name: Run E2E tests
        run: bun run e2e:test --reporter=line,html
        env:
          CI: 'true'

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: app/playwright-report
          if-no-files-found: warn

      - name: Upload per-test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-artifacts
          path: |
            app/tests/e2e/artifacts
            app/test-results/per-test-logs
          if-no-files-found: warn


